
name: Code Quality Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  wx-4-0-ubuntu:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup dependencies
        run: |
          sudo apt install python3-wxgtk4.0
          python3 -m pip install pylint mypy

      - name: check code
        run: python3 build.py -t check-code -V

  wx-4-1-1-ubuntu:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup dependencies
        run: |
          sudo apt install libgtk-3-dev
          python3 -m pip install pylint mypy attrdict3
          # build fails if attrdict is not installed before preparing wxPython
          python3 -m pip install wxPython==4.1.1

      - name: check code
        run: python3 build.py -t check-code -V

  wx-latest-ubuntu:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup dependencies
        run: |
          sudo apt install libgtk-3-dev
          python3 -m pip install pylint mypy attrdict3
          # build fails if attrdict is not installed before preparing wxPython
          python3 -m pip install wxPython

      - name: check code
        run: python3 build.py -t check-code -V

  #~ wx-latest-windows:
    #~ runs-on: windows-2019
    #~ defaults:
      #~ run:
        #~ shell: cmd

    #~ steps:
      #~ - name: checkout
        #~ uses: actions/checkout@v3

      #~ - name: setup Python
        #~ uses: actions/setup-python@v3.1.3

      #~ - name: setup dependencies
        #~ run: |
          #~ python -m pip install wheel setuptools attrdict3 requests pylint mypy
          #~ python -m pip install wxPython

      #~ - name: check code
        #~ run: python build.py -t check-code -V

  wx-latest-msys:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup MSYS2 & dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-wxPython
            mingw-w64-x86_64-python-pylint
            mingw-w64-x86_64-mypy

      - name: check code
        run: python3 build.py -t check-code -V
