
name: Deploy Release

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  dist-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure
        run: |
          package=$(grep "^package = " build.conf | head -n 1 | sed -e 's/^package = //')
          version=$(python3 build.py -v)
          if [[ "${{ github.ref_name }}" =~ ^v[0-9] ]]; then
            echo "using GitHub ref version ..."
            version=$(echo ${{ github.ref_name }} | sed 's/^v//')
          fi
          echo "configuring ${package} version ${version} ..."
          echo "ver=${version}" >> $GITHUB_ENV

      - name: install build dependencies
        run: sudo apt install debhelper devscripts

      - name: build source package
        run: python3 build.py -t dist-source -V

      - name: build portable package
        run: python3 build.py -t dist-bin -V

      - name: build .deb package
        run: python3 build.py -t dist-deb -V

      - name: prepare release information
        run: echo -e "Changes:\n\n$(python3 build.py -t changes)" > release_notes.tmp

      - name: publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: 'Version ${{ env.ver }}'
          body_path: release_notes.tmp
          files: build/dist/*
          prerelease: true
