
name: Deploy Release

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  dist-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: |
          version=$(echo ${{ github.ref_name }})
          if [[ "${version}" =~ ^v[0-9] ]]; then
            echo "using GitHub ref version ..."
            version=$(echo ${version} | sed 's/^v//')
            sed -i -e "s/^version = .*$/version = ${version}/" build.conf
          fi
          version=$(grep "^version = " build.conf | sed -e 's/^version = //')
          echo "configuring character generator version ${version} ..."
          echo "ver=${version}" >> $GITHUB_ENV
